name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install jayvee
      # - name: Set up Jayvee
      #   run: |
      #     ./grading/ci/setup_jayvee.sh

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # Run tests
      - name: Run tests
        run: |
          ./project/tests.sh
