name: Continuous Integration Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install jayvee
      - name: Set up Jayvee
        run: |
          npm install -g @jvalue/jayvee-interpreter

      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install pandas

      # Run tests
      - name: Run tests
        run: |
          chmod u+r+x ./project/tests.sh
          cd ./project
          ./tests.sh
